# Generated by Django 5.2.8 on 2025-11-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_type', models.CharField(choices=[('full', 'Полный пакет'), ('references', 'Базовые справочники'), ('products', 'Товары'), ('staff', 'Сотрудники'), ('contracts', 'Договоры'), ('suppliers', 'Поставщики'), ('storage', 'Места хранения'), ('transport', 'Транспорт')], default='full', max_length=32)),
                ('direction', models.CharField(choices=[('inbound', 'Входящий пакет'), ('outbound', 'Исходящий пакет')], default='inbound', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В работе'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_sync_jobs', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Обмен с ГК',
                'verbose_name_plural': 'Обмен с ГК',
                'ordering': ['-created_at'],
            },
        ),
    ]
