# Generated by Django 5.2.8 on 2025-11-18 10:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expires_at', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='inventory.productbatch')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('executed', 'Выполнен'), ('stopped', 'Стоп-лист')], default='draft', max_length=16)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_orders', to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_point', models.CharField(default='МХ-001', max_length=128)),
                ('price_type', models.CharField(choices=[('regular', 'Регулярная'), ('markdown', 'Уценка'), ('promo', 'Акция')], default='regular', max_length=16)),
                ('input_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label_type', models.CharField(choices=[('white', 'Белый'), ('yellow', 'Жёлтый'), ('promo', 'Акционный')], default='white', max_length=16)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.product')),
                ('stock_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockarea')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=6)),
                ('max_daily_change_percent', models.DecimalField(decimal_places=2, default=Decimal('90'), max_digits=6)),
                ('allow_auto_markdown', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_restriction', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCommandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(default='white', max_length=16)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricecommand')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.coupon')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_items', to='pricing.pricelist')),
            ],
            options={
                'unique_together': {('command', 'price')},
            },
        ),
        migrations.CreateModel(
            name='StopListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_point', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('blocked_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'trading_point')},
            },
        ),
    ]
