# Generated by Django 5.2.8 on 2025-11-20 16:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128, unique=True)),
                ('max_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=6)),
                ('max_daily_change_percent', models.DecimalField(decimal_places=2, default=Decimal('90'), max_digits=6)),
                ('allow_auto_markdown', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ограничение категории',
                'verbose_name_plural': 'Ограничения категорий',
            },
        ),
        migrations.AddField(
            model_name='pricecommand',
            name='print_payload',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricecommand',
            name='print_status',
            field=models.CharField(choices=[('pending', 'Ожидает печати'), ('printed', 'Отправлен в печать')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='pricecommand',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
