# Generated by Django 5.2.8 on 2025-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_categoryrestriction_pricecommand_print_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecommand',
            name='trading_point',
            field=models.CharField(default='МХ-001', max_length=128),
        ),
    ]
