# Generated by Django 5.2.8 on 2025-11-20 16:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricecommand_trading_point'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128, unique=True)),
                ('max_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=6)),
                ('max_daily_change_percent', models.DecimalField(decimal_places=2, default=Decimal('90'), max_digits=6)),
                ('markup_cap_percent', models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Максимальная наценка относительно входной цены (например 15 для 15%).', max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryRestriction',
        ),
        migrations.RemoveField(
            model_name='pricecommand',
            name='print_payload',
        ),
        migrations.RemoveField(
            model_name='pricecommand',
            name='print_status',
        ),
        migrations.AddField(
            model_name='pricecommand',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_price_orders', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='source',
            field=models.CharField(choices=[('hq', 'ГК'), ('supplier', 'Поставщик'), ('analytics', 'Аналитика'), ('local', 'МХ')], default='hq', max_length=16),
        ),
    ]
