# Generated by Django 5.2.8 on 2025-11-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('references', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='references.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='references.manufacturer'),
        ),
        migrations.AddField(
            model_name='inventoryline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='contract_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.contractitem'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockarea',
            name='parent_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='references.storagelocation'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='stock_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.stockarea'),
        ),
        migrations.AddField(
            model_name='inventoryline',
            name='stock_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockarea'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='stock_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.stockarea'),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='source_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_operations', to='inventory.stockarea'),
        ),
        migrations.AddField(
            model_name='stockoperation',
            name='target_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_operations', to='inventory.stockarea'),
        ),
        migrations.AddField(
            model_name='writeoffact',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_write_offs', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='writeoffact',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='writeoffact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='writeoffact',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('stock_area', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('batch', 'stock_area')},
        ),
    ]
