# Generated by Django 5.2.8 on 2025-11-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('references', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('shelf_life_ok', models.BooleanField(default=True)),
                ('batch_code_hint', models.CharField(blank=True, max_length=64)),
                ('input_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('waiting_hq', 'Ожидает решения ГК')], default='pending', max_length=16)),
                ('batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_link', to='inventory.productbatch')),
                ('contract_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.contractitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('stock_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivingDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discrepancy_type', models.CharField(choices=[('quantity', 'Количество'), ('quality', 'Качество/ассортимент'), ('expiration', 'Срок годности'), ('damage', 'Повреждение'), ('other', 'Другое')], default='other', max_length=32)),
                ('description', models.TextField()),
                ('reported_to_hq', models.BooleanField(default=False)),
                ('hq_ticket', models.CharField(blank=True, max_length=64)),
                ('decision', models.CharField(choices=[('pending', 'Ожидает решения'), ('accept', 'Принять товар'), ('reject', 'Отказать в приёмке')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancy_decisions', to='staff.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory.receivingitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('expected_arrival', models.DateField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivings', to='staff.employee')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_receivings', to='staff.employee')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.storagelocation')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.supplier')),
            ],
            options={
                'ordering': ['-expected_arrival', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.receivingorder'),
        ),
        migrations.CreateModel(
            name='StockPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='inventory.shelf')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='inventory.stockitem')),
            ],
            options={
                'unique_together': {('stock_item', 'shelf')},
            },
        ),
    ]
