# Generated by Django 5.2.8 on 2025-11-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delta_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='attendance.attendancereport')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Больничный'), ('unpaid', 'Отпуск без содержания')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('documents_provided', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='staff.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('weekdays', models.JSONField(default=dict)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.position')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='system', max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='staff.employee')),
            ],
        ),
    ]
