# Generated by Django 5.2.8 on 2025-11-20 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На подтверждении'), ('approved', 'Подтверждён')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='tolerance_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='attendancereportline',
            name='adjustment_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancereportline',
            name='approved_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignment', to='staff.employee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='attendance.scheduletemplate')),
            ],
        ),
    ]
